# Generated by Django 4.2.11 on 2024-06-13 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nominal_diameter', models.IntegerField(blank=True, null=True)),
                ('outer_diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wall_thickness', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=4), size=None)),
                ('weight_per_meter', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), size=None)),
                ('quality_standard', models.CharField(max_length=100)),
            ],
        ),
    ]
