[tool.poetry]
name = "ovhomelab"
version = "0.1.0"
description = ""
authors = ["Юрий <polyanskii2118@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
